## Assignment 7 - A43

In [1]:
import numpy as np

In [2]:
#Define Sigmoid Activation Function - Sigmoid squashes inputs into range (0,1).gives the slope at each output, used to adjust weights in the right direction.
def sigmoid(x):
    return 1/(1+ np.exp(-x))

#Define Derivative of Sigmoid Activution Function - derivative is used in backpropagation to compute gradients efficiently.
def sigmoid_derivative(x):
    return x * (1-x)

#Define XOR Function Dataset - XOR truth table (non-linearly separable)
X= np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y= np.array([[0], [1], [1], [0]])

# Define Neural Network Architecture
input_layer_size = 2
hidden_layer_size = 2
output_layer_size = 1

# Initialize Weights and Biases
weights1 = np.random.uniform(size=(input_layer_size, hidden_layer_size))
bias1 = np.random.uniform(size=(1, hidden_layer_size))
weights2 = np.random.uniform(size=(hidden_layer_size, output_layer_size))
bias2 = np.random.uniform(size=(1, output_layer_size))

# Define Learning Rate and Number of Epochs
learning_rate = 0.1
epochs = 10000

In [3]:
#Train Neural Network with Back Propagation Algorithm
for epoch in range(epochs):
    #Forward Propagation
    hidden_layer_output = sigmoid(np.dot(X, weights1) + bias1)
    output_layer_output = sigmoid(np.dot(hidden_layer_output, weights2) + bias2)
    
    #Back Propagation
    error = y - output_layer_output
    output_layer_delta = error * sigmoid_derivative(output_layer_output)
    hidden_layer_error = output_layer_delta.dot(weights2.T)
    hidden_layer_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)

    #Update Weights and Biases
    weights2 += hidden_layer_output.T.dot(output_layer_delta) * learning_rate
    bias2 += np.sum(output_layer_delta, axis=0, keepdims=True) * learning_rate
    weights1 += X.T.dot(hidden_layer_delta) * learning_rate
    bias1+= np.sum(hidden_layer_delta, axis=0, keepdims=True) * learning_rate
    
    if epoch % 2000 == 0:
        print(f"\nEpoch {epoch}")
        print("Weights1:\n", weights1)
        print("Bias1:", bias1)
        print("Weights2:\n", weights2)
        print("Bias2:", bias2)


Epoch 0
Weights1:
 [[0.02119187 0.5149922 ]
 [0.75854798 0.78866994]]
Bias1: [[0.04099218 0.58861011]]
Weights2:
 [[0.72085734]
 [0.07021952]]
Bias2: [[-0.00618569]]

Epoch 2000
Weights1:
 [[0.54800622 0.80911086]
 [0.86083549 0.98421991]]
Bias1: [[0.16236759 0.60187012]]
Weights2:
 [[0.40437766]
 [0.46240382]]
Bias2: [[-0.63255334]]

Epoch 4000
Weights1:
 [[1.2641574  2.76146599]
 [1.38732132 2.77526048]]
Bias1: [[ 0.38583324 -0.21578426]]
Weights2:
 [[0.19045886]
 [2.31915117]]
Bias2: [[-1.98186919]]

Epoch 6000
Weights1:
 [[1.45618267 4.766788  ]
 [1.51448768 4.79774522]]
Bias1: [[-1.82017726 -0.98937715]]
Weights2:
 [[-3.04934301]
 [ 4.61584808]]
Bias2: [[-2.45935141]]

Epoch 8000
Weights1:
 [[3.10896313 5.49309146]
 [3.11149112 5.51111463]]
Bias1: [[-4.68760845 -2.00504569]]
Weights2:
 [[-6.64059418]
 [ 6.39733228]]
Bias2: [[-2.92102259]]


In [4]:
#Predict XOR Function
predictions = sigmoid(np.dot(sigmoid(np.dot(X, weights1) + bias1), weights2) + bias2)
print(predictions.round())

[[0.]
 [1.]
 [1.]
 [0.]]


In [5]:
# Use ReLU activation in hidden layer:
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def tanh(x): return np.tanh(x)
def tanh_derivative(x): return 1 - x ** 2